version: '3'
services:
  app:
    container_name: shoppingApp
    restart: always
    build: .
    ports:
      - '5050:5050'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  