version: '3'
services:
  app:
    container_name: shopping_list_backend
    restart: always
    build: .
    ports:
      - '7000:7000'
    networks:
      - main

networks:
  main:
    driver: bridge
