name: Docker Build and Run
on:
  push:
    tags:
      - "shopping-backend"
    branches:
      - main

jobs:
  build-and-run:
    runs-on: shopping-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Stop Container
        continue-on-error: true
        run: sudo docker stop shopping_list_backend

      - name: Remove Container
        continue-on-error: true
        run: sudo docker rm shopping_list_backend

      - name: Remove Image
        continue-on-error: true
        run: sudo docker image rm shopping_list_backend

      - name: Compose Docker Image
        run: sudo docker-compose up -d

      - name: Connect to Docker Network
        run: sudo docker network connect main shopping_list_backend
